machine:
  imageName: pytorch/pytorch
  containerDiskSize: 40
  volumeSize: 40
  gpuCount: 2
  gpuTypeId: "NVIDIA GeForce RTX 3090"
  minVcpuCount: 2
  minMemoryInGb: 8
runpod_api:
  API_KEY: ''
  URL: https://api.runpod.io/graphql
cloudType: "COMMUNITY"
spot: true